#!/bin/sh
echo "Running Spotless check..."

# Run Spotless check
mvn spotless:check

if [ $? -ne 0 ]; then
  echo "❌ Spotless check failed. Applying formatting..."

  mvn spotless:apply

  git add .

  mvn spotless:check
  if [ $? -ne 0 ]; then
    echo "❌ Spotless still failed after applying formatting. Please check your code."
    exit 1
  fi

  echo "✅ Spotless formatting applied successfully!"
else
  echo "✅ Spotless check passed! No formatting issues."
fi

# Run Checkstyle check
echo "Running Checkstyle check..."

mvn checkstyle:check

if [ $? -ne 0 ]; then
  echo "❌ Checkstyle check failed. Please check your code and fix the issues."
  exit 1
fi

echo "✅ Checkstyle check passed! No issues found."

exit 0
