version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      fhir_version: 'R4'
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_CONFIG_LOCATION: "classpath:/application-custom.yaml"

      # Enable these for MySQL
      # SPRING_DATASOURCE_URL: "jdbc:mysql://hapi-fhir-mysql:3306/hapi"
      # SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.jdbc.Driver
      # SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.HapiFhirMySQLDialect"

      # Enable these for PostgreSQL
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"

      OAUTH_ENABLED: true
      OAUTH_CLIENT_ID: fhir4-api
      OAUTH_USER_ROLE: fhir4-user
      OAUTH_ADMIN_ROLE: fhir4-admin
      OAUTH_JWKS_URL: http://keycloak-url/auth/realms/product/protocol/openid-connect/certs
      OAUTH_AUTHORIZE_URL: http://keycloak-url/auth/realms/product/protocol/openid-connect/auth
      OAUTH_TOKEN_URL: http://keycloak-url/auth/realms/product/protocol/openid-connect/token
      OAUTH_MANAGE_URL: http://keycloak-url/auth/realms/product/account
      SMART_ISSUER: http://keycloak-url/auth/realms/product
      SMART_JWKS_URL: http://keycloak-url/auth/realms/product/protocol/openid-connect/certs
      SMART_AUTHORIZATION_URL: http://keycloak-url/auth/realms/product/protocol/openid-connect/auth
      SMART_TOKEN_URL: http://keycloak-url/auth/realms/product/protocol/openid-connect/token
      SMART_INTROSPECTION_URL: http://keycloak-url/auth/realms/product/protocol/openid-connect/token/introspect
      SMART_REVOCATION_URL: http://keycloak-url/auth/realms/product/protocol/openid-connect/revoke
      SMART_MANAGE_URL: http://keycloak-url/auth/realms/product/account
    ports:
      - "8080:8080"
  # hapi-fhir-mysql:
  #   platform: linux/x86_64
  #   image: mysql:5.7
  #   container_name: hapi-fhir-mysql
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: "hapi"
  #     MYSQL_USER: "admin"
  #     MYSQL_PASSWORD: "admin"
  #     MYSQL_ROOT_PASSWORD: "admin"
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - hapi-fhir-mysql:/var/lib/mysql
  hapi-fhir-postgres:
    image: postgres:15-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  # hapi-fhir-mysql:
  hapi-fhir-postgres:
