version: "3"
services:
  hapi-fhir-jpaserver-start:
    network_mode: host
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      APIKEY: '<apiKey>'
      APIKEY_ENABLED: 'false'
      datasource.driver: 'com.mysql.jdbc.Driver'
      datasource.password: 'admin'
      datasource.url: 'jdbc:mysql://localhost:3306/hapi'
      datasource.username: 'admin'
      enable_web: 'true'
      fhir_version: 'R4'
      hapi.fhir.server_address: 'http://localhost:8080/fhir/'
      hibernate.dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
      OAUTH_CLIENT_ID: '<oauth_clientId>'
      OAUTH_ENABLED: 'false'
      OAUTH_URL: '<oauth_server_url>'
      OAUTH_USER_ROLE: '<oauth_user_role>'
      reuse_cached_search_results_millis: '0'
      spring.config.location: '/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application-custom.yaml'
      subscription.resthook.enabled: 'true'
      subscription.websocket.enabled: 'true'
  hapi-fhir-mysql:
    network_mode: host
    image: mysql:latest
    container_name: hapi-fhir-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql
volumes:
  hapi-fhir-mysql:
